### ISSUE TITLE
TypeError: Cannot call method 'join' of undefined

### ISSUE THREAD

**Issue by martinhearn** [haydenbbickerton/feature-requests-app#1]
Hi

I am trying to install the frontend but I get this error when running `npm run dev`

I've run out of ideas (not massively experienced with npm) on how to solve this...

Thanks!

```
[vagrant@vagrantbox feature-requests-app]$ npm run dev

> feature-requests-app@0.1.0 dev /var/www/laravelvue/feature-requests-app
> node build/dev-server.js


/var/www/laravelvue/feature-requests-app/build/utils.js:6
  return path.posix.join(config.build.assetsSubDirectory, _path)
                    ^
TypeError: Cannot call method 'join' of undefined
    at Object.exports.assetsPath (/var/www/laravelvue/feature-requests-app/build/utils.js:6:21)
    at Object.<anonymous> (/var/www/laravelvue/feature-requests-app/build/webpack.base.conf.js:75:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/laravelvue/feature-requests-app/build/webpack.dev.conf.js:4:25)
    at Module._compile (module.js:456:26)

npm ERR! Linux 3.10.0-327.13.1.el7.x86_64
npm ERR! argv "node" "/usr/bin/npm" "run" "dev"
npm ERR! node v0.10.42
npm ERR! npm  v3.8.7
npm ERR! code ELIFECYCLE
npm ERR! feature-requests-app@0.1.0 dev: `node build/dev-server.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the feature-requests-app@0.1.0 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the feature-requests-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs feature-requests-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls feature-requests-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/laravelvue/feature-requests-app/npm-debug.log
```

**Comment by haydenbbickerton** [comment]
[Node doesn't have posix in v0.10](https://nodejs.org/docs/latest-v0.10.x/api/path.html). Any chance you could update?

**Comment by martinhearn** [comment]
thanks - that fixed it :)
